01-25 08:14:32 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Table PROCESSEXECUTIONSTATEINFORMATION not found; SQL statement: SELECT COUNT(*) FROM ProcessExecutionStateInformation r WHERE r.restartID = 0
 AND r.ExecutionState = 1 AND NOT EXISTS ( SELECT * FROM ProcessExecutionStateInformation s WHERE 
 r.ProcessID = s.ProcessID AND r.RequestID = s.RequestID AND s.ExecutionState <> 1 ) [42S02-36]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.parse(Parser.java:224)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:61)
	at org.executequery.databasemediators.QuerySender.getResultSet(QuerySender.java:313)
	at org.executequery.databasemediators.QuerySender.executeQuery(QuerySender.java:856)
	at org.executequery.gui.editor.QueryAnalyser.executeSQL(QueryAnalyser.java:501)
	at org.executequery.gui.editor.QueryAnalyser.access$000(QueryAnalyser.java:66)
	at org.executequery.gui.editor.QueryAnalyser$1.construct(QueryAnalyser.java:298)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
org.h2.jdbc.JdbcSQLException: Table PROCESSEXECUTIONSTATEINFORMATION not found [42S02-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.schema.Schema.getTableOrView(Schema.java:199)
	at org.h2.command.Parser.readTableFilter(Parser.java:743)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1213)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:1280)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1207)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1094)
	at org.h2.command.Parser.parseSelect(Parser.java:1075)
	at org.h2.command.Parser.parse(Parser.java:332)
	at org.h2.command.Parser.parse(Parser.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:61)
	at org.executequery.databasemediators.QuerySender.getResultSet(QuerySender.java:313)
	at org.executequery.databasemediators.QuerySender.executeQuery(QuerySender.java:856)
	at org.executequery.gui.editor.QueryAnalyser.executeSQL(QueryAnalyser.java:501)
	at org.executequery.gui.editor.QueryAnalyser.access$000(QueryAnalyser.java:66)
	at org.executequery.gui.editor.QueryAnalyser$1.construct(QueryAnalyser.java:298)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
01-25 08:18:42 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Column AND not found; SQL statement: SELECT COUNT(*) FROM ProcessExecutionStateInformation r WHERE r.RequestID =0  AND r.restartID = 0
 AND r.ExecutionState = 1 AND AND NOT EXISTS ( SELECT * FROM ProcessExecutionStateInformation s WHERE 
 r.ProcessID = s.ProcessID AND r.RequestID = s.RequestID AND s.ExecutionState <> 1 ) [42S22-36]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.prepareCommand(Parser.java:210)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:61)
	at org.executequery.databasemediators.QuerySender.getResultSet(QuerySender.java:313)
	at org.executequery.databasemediators.QuerySender.executeQuery(QuerySender.java:856)
	at org.executequery.gui.editor.QueryAnalyser.executeSQL(QueryAnalyser.java:501)
	at org.executequery.gui.editor.QueryAnalyser.access$000(QueryAnalyser.java:66)
	at org.executequery.gui.editor.QueryAnalyser$1.construct(QueryAnalyser.java:298)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
org.h2.jdbc.JdbcSQLException: Column AND not found [42S22-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:110)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:104)
	at org.h2.command.dml.Select.prepare(Select.java:464)
	at org.h2.command.Parser.prepareCommand(Parser.java:190)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:61)
	at org.executequery.databasemediators.QuerySender.getResultSet(QuerySender.java:313)
	at org.executequery.databasemediators.QuerySender.executeQuery(QuerySender.java:856)
	at org.executequery.gui.editor.QueryAnalyser.executeSQL(QueryAnalyser.java:501)
	at org.executequery.gui.editor.QueryAnalyser.access$000(QueryAnalyser.java:66)
	at org.executequery.gui.editor.QueryAnalyser$1.construct(QueryAnalyser.java:298)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
01-25 08:18:43 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Column AND not found; SQL statement: SELECT COUNT(*) FROM ProcessExecutionStateInformation r WHERE r.RequestID =0  AND r.restartID = 0
 AND r.ExecutionState = 1 AND AND NOT EXISTS ( SELECT * FROM ProcessExecutionStateInformation s WHERE 
 r.ProcessID = s.ProcessID AND r.RequestID = s.RequestID AND s.ExecutionState <> 1 ) [42S22-36]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.prepareCommand(Parser.java:210)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:61)
	at org.executequery.databasemediators.QuerySender.getResultSet(QuerySender.java:313)
	at org.executequery.databasemediators.QuerySender.executeQuery(QuerySender.java:856)
	at org.executequery.gui.editor.QueryAnalyser.executeSQL(QueryAnalyser.java:501)
	at org.executequery.gui.editor.QueryAnalyser.access$000(QueryAnalyser.java:66)
	at org.executequery.gui.editor.QueryAnalyser$1.construct(QueryAnalyser.java:298)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
org.h2.jdbc.JdbcSQLException: Column AND not found [42S22-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:110)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:104)
	at org.h2.command.dml.Select.prepare(Select.java:464)
	at org.h2.command.Parser.prepareCommand(Parser.java:190)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:61)
	at org.executequery.databasemediators.QuerySender.getResultSet(QuerySender.java:313)
	at org.executequery.databasemediators.QuerySender.executeQuery(QuerySender.java:856)
	at org.executequery.gui.editor.QueryAnalyser.executeSQL(QueryAnalyser.java:501)
	at org.executequery.gui.editor.QueryAnalyser.access$000(QueryAnalyser.java:66)
	at org.executequery.gui.editor.QueryAnalyser$1.construct(QueryAnalyser.java:298)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
01-25 08:19:17 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Column AND not found; SQL statement: SELECT COUNT(*) FROM ProcessExecutionStateInformation r WHERE r.restartID = 0
 AND r.ExecutionState = 1 AND AND NOT EXISTS ( SELECT * FROM ProcessExecutionStateInformation s WHERE 
 r.ProcessID = s.ProcessID AND r.RequestID = s.RequestID AND s.ExecutionState <> 1 ) [42S22-36]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.prepareCommand(Parser.java:210)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:61)
	at org.executequery.databasemediators.QuerySender.getResultSet(QuerySender.java:313)
	at org.executequery.databasemediators.QuerySender.executeQuery(QuerySender.java:856)
	at org.executequery.gui.editor.QueryAnalyser.executeSQL(QueryAnalyser.java:501)
	at org.executequery.gui.editor.QueryAnalyser.access$000(QueryAnalyser.java:66)
	at org.executequery.gui.editor.QueryAnalyser$1.construct(QueryAnalyser.java:298)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
org.h2.jdbc.JdbcSQLException: Column AND not found [42S22-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:110)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:104)
	at org.h2.command.dml.Select.prepare(Select.java:464)
	at org.h2.command.Parser.prepareCommand(Parser.java:190)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:61)
	at org.executequery.databasemediators.QuerySender.getResultSet(QuerySender.java:313)
	at org.executequery.databasemediators.QuerySender.executeQuery(QuerySender.java:856)
	at org.executequery.gui.editor.QueryAnalyser.executeSQL(QueryAnalyser.java:501)
	at org.executequery.gui.editor.QueryAnalyser.access$000(QueryAnalyser.java:66)
	at org.executequery.gui.editor.QueryAnalyser$1.construct(QueryAnalyser.java:298)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
01-25 08:19:17 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Column AND not found; SQL statement: SELECT COUNT(*) FROM ProcessExecutionStateInformation r WHERE r.restartID = 0
 AND r.ExecutionState = 1 AND AND NOT EXISTS ( SELECT * FROM ProcessExecutionStateInformation s WHERE 
 r.ProcessID = s.ProcessID AND r.RequestID = s.RequestID AND s.ExecutionState <> 1 ) [42S22-36]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.prepareCommand(Parser.java:210)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:61)
	at org.executequery.databasemediators.QuerySender.getResultSet(QuerySender.java:313)
	at org.executequery.databasemediators.QuerySender.executeQuery(QuerySender.java:856)
	at org.executequery.gui.editor.QueryAnalyser.executeSQL(QueryAnalyser.java:501)
	at org.executequery.gui.editor.QueryAnalyser.access$000(QueryAnalyser.java:66)
	at org.executequery.gui.editor.QueryAnalyser$1.construct(QueryAnalyser.java:298)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
org.h2.jdbc.JdbcSQLException: Column AND not found [42S22-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:110)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:104)
	at org.h2.command.dml.Select.prepare(Select.java:464)
	at org.h2.command.Parser.prepareCommand(Parser.java:190)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:61)
	at org.executequery.databasemediators.QuerySender.getResultSet(QuerySender.java:313)
	at org.executequery.databasemediators.QuerySender.executeQuery(QuerySender.java:856)
	at org.executequery.gui.editor.QueryAnalyser.executeSQL(QueryAnalyser.java:501)
	at org.executequery.gui.editor.QueryAnalyser.access$000(QueryAnalyser.java:66)
	at org.executequery.gui.editor.QueryAnalyser$1.construct(QueryAnalyser.java:298)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
01-25 08:19:23 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Column AND not found; SQL statement: SELECT COUNT(*) FROM ProcessExecutionStateInformation r WHERE r.restartID = 0
 AND r.ExecutionState = 1 AND AND NOT EXISTS ( SELECT * FROM ProcessExecutionStateInformation s WHERE 
 r.ProcessID = s.ProcessID AND r.RequestID = s.RequestID AND s.ExecutionState <> 1 ) [42S22-36]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.prepareCommand(Parser.java:210)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:61)
	at org.executequery.databasemediators.QuerySender.getResultSet(QuerySender.java:313)
	at org.executequery.databasemediators.QuerySender.executeQuery(QuerySender.java:856)
	at org.executequery.gui.editor.QueryAnalyser.executeSQL(QueryAnalyser.java:501)
	at org.executequery.gui.editor.QueryAnalyser.access$000(QueryAnalyser.java:66)
	at org.executequery.gui.editor.QueryAnalyser$1.construct(QueryAnalyser.java:298)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
org.h2.jdbc.JdbcSQLException: Column AND not found [42S22-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:110)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:104)
	at org.h2.command.dml.Select.prepare(Select.java:464)
	at org.h2.command.Parser.prepareCommand(Parser.java:190)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:61)
	at org.executequery.databasemediators.QuerySender.getResultSet(QuerySender.java:313)
	at org.executequery.databasemediators.QuerySender.executeQuery(QuerySender.java:856)
	at org.executequery.gui.editor.QueryAnalyser.executeSQL(QueryAnalyser.java:501)
	at org.executequery.gui.editor.QueryAnalyser.access$000(QueryAnalyser.java:66)
	at org.executequery.gui.editor.QueryAnalyser$1.construct(QueryAnalyser.java:298)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
01-25 08:19:24 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Column AND not found; SQL statement: SELECT COUNT(*) FROM ProcessExecutionStateInformation r WHERE r.restartID = 0
 AND r.ExecutionState = 1 AND AND NOT EXISTS ( SELECT * FROM ProcessExecutionStateInformation s WHERE 
 r.ProcessID = s.ProcessID AND r.RequestID = s.RequestID AND s.ExecutionState <> 1 ) [42S22-36]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.prepareCommand(Parser.java:210)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:61)
	at org.executequery.databasemediators.QuerySender.getResultSet(QuerySender.java:313)
	at org.executequery.databasemediators.QuerySender.executeQuery(QuerySender.java:856)
	at org.executequery.gui.editor.QueryAnalyser.executeSQL(QueryAnalyser.java:501)
	at org.executequery.gui.editor.QueryAnalyser.access$000(QueryAnalyser.java:66)
	at org.executequery.gui.editor.QueryAnalyser$1.construct(QueryAnalyser.java:298)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
org.h2.jdbc.JdbcSQLException: Column AND not found [42S22-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:110)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:104)
	at org.h2.command.dml.Select.prepare(Select.java:464)
	at org.h2.command.Parser.prepareCommand(Parser.java:190)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:61)
	at org.executequery.databasemediators.QuerySender.getResultSet(QuerySender.java:313)
	at org.executequery.databasemediators.QuerySender.executeQuery(QuerySender.java:856)
	at org.executequery.gui.editor.QueryAnalyser.executeSQL(QueryAnalyser.java:501)
	at org.executequery.gui.editor.QueryAnalyser.access$000(QueryAnalyser.java:66)
	at org.executequery.gui.editor.QueryAnalyser$1.construct(QueryAnalyser.java:298)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
01-25 08:26:51 database: opening /home/ic/estevao/Desktop/integrade-0.3-rc1/clusterManagement/grm/database/ExecutionManager
org.h2.jdbc.JdbcSQLException: Database may be already open: Lock file modified in the future: dist=-36495 [90020-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.waitUntilOld(FileLock.java:142)
	at org.h2.store.FileLock.lockFile(FileLock.java:163)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:424)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:290)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:267)
	at org.executequery.datasource.ConnectionPool.ensureCapacity(ConnectionPool.java:291)
	at org.executequery.datasource.ConnectionManager.createDataSource(ConnectionManager.java:90)
	at org.executequery.databasemediators.ConnectionBuilder.connect(ConnectionBuilder.java:133)
	at org.executequery.databasemediators.ConnectionBuilder.access$000(ConnectionBuilder.java:44)
	at org.executequery.databasemediators.ConnectionBuilder$1.construct(ConnectionBuilder.java:117)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
01-25 08:26:55 database: opening /home/ic/estevao/Desktop/integrade-0.3-rc1/clusterManagement/grm/database/ExecutionManager
org.h2.jdbc.JdbcSQLException: Database may be already open: Lock file modified in the future: dist=-32909 [90020-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.waitUntilOld(FileLock.java:142)
	at org.h2.store.FileLock.lockFile(FileLock.java:163)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:424)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:290)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:267)
	at org.executequery.datasource.ConnectionPool.ensureCapacity(ConnectionPool.java:291)
	at org.executequery.datasource.ConnectionManager.createDataSource(ConnectionManager.java:90)
	at org.executequery.databasemediators.ConnectionBuilder.connect(ConnectionBuilder.java:133)
	at org.executequery.databasemediators.ConnectionBuilder.access$000(ConnectionBuilder.java:44)
	at org.executequery.databasemediators.ConnectionBuilder$1.construct(ConnectionBuilder.java:117)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
01-25 08:27:46 database: opening /home/ic/estevao/Desktop/integrade-0.3-rc1/clusterManagement/grm/database/ExecutionManager
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:424)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:290)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:267)
	at org.executequery.datasource.ConnectionPool.ensureCapacity(ConnectionPool.java:291)
	at org.executequery.datasource.ConnectionManager.createDataSource(ConnectionManager.java:90)
	at org.executequery.databasemediators.ConnectionBuilder.connect(ConnectionBuilder.java:133)
	at org.executequery.databasemediators.ConnectionBuilder.access$000(ConnectionBuilder.java:44)
	at org.executequery.databasemediators.ConnectionBuilder$1.construct(ConnectionBuilder.java:117)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
01-25 08:28:15 database: opening /home/ic/estevao/Desktop/integrade-0.3-rc1/clusterManagement/grm/database/ExecutionManager
org.h2.jdbc.JdbcSQLException: Database may be already open: Lock file modified in the future: dist=-73174 [90020-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.waitUntilOld(FileLock.java:142)
	at org.h2.store.FileLock.lockFile(FileLock.java:163)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:424)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:290)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:267)
	at org.executequery.datasource.ConnectionPool.ensureCapacity(ConnectionPool.java:291)
	at org.executequery.datasource.ConnectionManager.createDataSource(ConnectionManager.java:90)
	at org.executequery.databasemediators.ConnectionBuilder.connect(ConnectionBuilder.java:133)
	at org.executequery.databasemediators.ConnectionBuilder.access$000(ConnectionBuilder.java:44)
	at org.executequery.databasemediators.ConnectionBuilder$1.construct(ConnectionBuilder.java:117)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
01-25 08:28:19 database: opening /home/ic/estevao/Desktop/integrade-0.3-rc1/clusterManagement/grm/database/ExecutionManager
org.h2.jdbc.JdbcSQLException: Database may be already open: Lock file modified in the future: dist=-69499 [90020-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.waitUntilOld(FileLock.java:142)
	at org.h2.store.FileLock.lockFile(FileLock.java:163)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:424)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:290)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:267)
	at org.executequery.datasource.ConnectionPool.ensureCapacity(ConnectionPool.java:291)
	at org.executequery.datasource.ConnectionManager.createDataSource(ConnectionManager.java:90)
	at org.executequery.databasemediators.ConnectionBuilder.connect(ConnectionBuilder.java:133)
	at org.executequery.databasemediators.ConnectionBuilder.access$000(ConnectionBuilder.java:44)
	at org.executequery.databasemediators.ConnectionBuilder$1.construct(ConnectionBuilder.java:117)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
01-25 08:28:27 database: opening /home/ic/estevao/Desktop/integrade-0.3-rc1/clusterManagement/grm/database/ExecutionManager
org.h2.jdbc.JdbcSQLException: Database may be already open: Lock file modified in the future: dist=-61399 [90020-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.waitUntilOld(FileLock.java:142)
	at org.h2.store.FileLock.lockFile(FileLock.java:163)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:424)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:290)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:267)
	at org.executequery.datasource.ConnectionPool.ensureCapacity(ConnectionPool.java:291)
	at org.executequery.datasource.ConnectionManager.createDataSource(ConnectionManager.java:90)
	at org.executequery.databasemediators.ConnectionBuilder.connect(ConnectionBuilder.java:133)
	at org.executequery.databasemediators.ConnectionBuilder.access$000(ConnectionBuilder.java:44)
	at org.executequery.databasemediators.ConnectionBuilder$1.construct(ConnectionBuilder.java:117)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
01-25 08:36:39 database: opening /home/ic/estevao/Desktop/integrade-0.3-rc1/clusterManagement/grm/database/ExecutionManager
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:424)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:193)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.connection(ExecutionDatabaseManager.java:761)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.registerApplicationExecution(ExecutionDatabaseManager.java:62)
	at grm.executionManager.ExecutionManagerImpl.setExecutionScheduled(ExecutionManagerImpl.java:71)
	at clusterManagement._ExecutionManagerStub.setExecutionScheduled(_ExecutionManagerStub.java:104)
	at grm.GrmImpl.requestRemoteExecution(GrmImpl.java:182)
	at clusterManagement.GrmPOA._invoke(GrmPOA.java:81)
	at org.jacorb.poa.RequestProcessor.invokeOperation(RequestProcessor.java:299)
	at org.jacorb.poa.RequestProcessor.process(RequestProcessor.java:593)
	at org.jacorb.poa.RequestProcessor.run(RequestProcessor.java:735)
01-25 09:53:06 database: opening /home/ic/estevao/Desktop/integrade-0.3-rc1/clusterManagement/grm/database/ExecutionManager
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:424)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:193)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.connection(ExecutionDatabaseManager.java:762)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.registerApplicationExecution(ExecutionDatabaseManager.java:62)
	at grm.executionManager.ExecutionManagerImpl.setExecutionScheduled(ExecutionManagerImpl.java:71)
	at clusterManagement._ExecutionManagerStub.setExecutionScheduled(_ExecutionManagerStub.java:104)
	at grm.GrmImpl.requestRemoteExecution(GrmImpl.java:182)
	at clusterManagement.GrmPOA._invoke(GrmPOA.java:81)
	at org.jacorb.poa.RequestProcessor.invokeOperation(RequestProcessor.java:299)
	at org.jacorb.poa.RequestProcessor.process(RequestProcessor.java:593)
	at org.jacorb.poa.RequestProcessor.run(RequestProcessor.java:735)
01-25 10:12:59 database: opening /home/ic/estevao/Desktop/integrade-0.3-rc1/clusterManagement/grm/database/ExecutionManager
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:424)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:193)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.connection(ExecutionDatabaseManager.java:761)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.registerApplicationExecution(ExecutionDatabaseManager.java:62)
	at grm.executionManager.ExecutionManagerImpl.setExecutionScheduled(ExecutionManagerImpl.java:71)
	at clusterManagement._ExecutionManagerStub.setExecutionScheduled(_ExecutionManagerStub.java:104)
	at grm.GrmImpl.requestRemoteExecution(GrmImpl.java:182)
	at clusterManagement.GrmPOA._invoke(GrmPOA.java:81)
	at org.jacorb.poa.RequestProcessor.invokeOperation(RequestProcessor.java:299)
	at org.jacorb.poa.RequestProcessor.process(RequestProcessor.java:593)
	at org.jacorb.poa.RequestProcessor.run(RequestProcessor.java:735)
02-08 16:54:05 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Check constraint violation: FOREIGN_1_REQUESTID_REPLICAID: PUBLIC.PROCESSEXECUTIONSTATEINFORMATION FOREIGN KEY(REQUESTID, REPLICAID) REFERENCES PUBLIC.APPLICATIONEXECUTIONSTATEINFORMATION(REQUESTID, REPLICAID) [23000-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:336)
	at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:352)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:230)
	at org.h2.table.Table.fireConstraints(Table.java:379)
	at org.h2.table.Table.fireAfterRow(Table.java:387)
	at org.h2.command.dml.Delete.update(Delete.java:75)
	at org.h2.command.CommandContainer.update(CommandContainer.java:64)
	at org.h2.command.Command.executeUpdate(Command.java:120)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:109)
	at org.executequery.databasemediators.QuerySender.updateRecords(QuerySender.java:1017)
	at org.executequery.databasemediators.QuerySender.executeQuery(QuerySender.java:868)
	at org.executequery.gui.editor.QueryAnalyser.executeSQL(QueryAnalyser.java:501)
	at org.executequery.gui.editor.QueryAnalyser.access$000(QueryAnalyser.java:66)
	at org.executequery.gui.editor.QueryAnalyser$1.construct(QueryAnalyser.java:298)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
02-08 16:54:05 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Check constraint violation: FOREIGN_2_REQUESTID: PUBLIC.APPLICATIONEXECUTIONSTATEINFORMATION FOREIGN KEY(REQUESTID) REFERENCES PUBLIC.APPLICATIONEXECUTIONINFORMATION(REQUESTID) [23000-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:336)
	at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:352)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:230)
	at org.h2.table.Table.fireConstraints(Table.java:379)
	at org.h2.table.Table.fireAfterRow(Table.java:387)
	at org.h2.command.dml.Delete.update(Delete.java:75)
	at org.h2.command.CommandContainer.update(CommandContainer.java:64)
	at org.h2.command.Command.executeUpdate(Command.java:120)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:109)
	at org.executequery.databasemediators.QuerySender.updateRecords(QuerySender.java:1017)
	at org.executequery.databasemediators.QuerySender.executeQuery(QuerySender.java:868)
	at org.executequery.gui.editor.QueryAnalyser.executeSQL(QueryAnalyser.java:501)
	at org.executequery.gui.editor.QueryAnalyser.access$000(QueryAnalyser.java:66)
	at org.executequery.gui.editor.QueryAnalyser$1.construct(QueryAnalyser.java:298)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
02-14 11:21:06 database: opening /home/ic/estevao/Desktop/integrade-0.3-rc1/clusterManagement/grm/database/ExecutionManager
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:424)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:290)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:267)
	at org.executequery.datasource.ConnectionPool.ensureCapacity(ConnectionPool.java:291)
	at org.executequery.datasource.ConnectionManager.createDataSource(ConnectionManager.java:90)
	at org.executequery.databasemediators.ConnectionBuilder.connect(ConnectionBuilder.java:133)
	at org.executequery.databasemediators.ConnectionBuilder.access$000(ConnectionBuilder.java:44)
	at org.executequery.databasemediators.ConnectionBuilder$1.construct(ConnectionBuilder.java:117)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
02-14 11:21:29 database: opening /home/ic/estevao/Desktop/integrade-0.3-rc1/clusterManagement/grm/database/ExecutionManager
org.h2.jdbc.JdbcSQLException: Database may be already open: Lock file modified in the future: dist=-19951 [90020-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.waitUntilOld(FileLock.java:142)
	at org.h2.store.FileLock.lockFile(FileLock.java:163)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:424)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:290)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:267)
	at org.executequery.datasource.ConnectionPool.ensureCapacity(ConnectionPool.java:291)
	at org.executequery.datasource.ConnectionManager.createDataSource(ConnectionManager.java:90)
	at org.executequery.databasemediators.ConnectionBuilder.connect(ConnectionBuilder.java:133)
	at org.executequery.databasemediators.ConnectionBuilder.access$000(ConnectionBuilder.java:44)
	at org.executequery.databasemediators.ConnectionBuilder$1.construct(ConnectionBuilder.java:117)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
02-14 11:21:36 database: opening /home/ic/estevao/Desktop/integrade-0.3-rc1/clusterManagement/grm/database/ExecutionManager
org.h2.jdbc.JdbcSQLException: Database may be already open: Lock file modified in the future: dist=-12960 [90020-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.waitUntilOld(FileLock.java:142)
	at org.h2.store.FileLock.lockFile(FileLock.java:163)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:424)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:290)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:267)
	at org.executequery.datasource.ConnectionPool.ensureCapacity(ConnectionPool.java:291)
	at org.executequery.datasource.ConnectionManager.createDataSource(ConnectionManager.java:90)
	at org.executequery.databasemediators.ConnectionBuilder.connect(ConnectionBuilder.java:133)
	at org.executequery.databasemediators.ConnectionBuilder.access$000(ConnectionBuilder.java:44)
	at org.executequery.databasemediators.ConnectionBuilder$1.construct(ConnectionBuilder.java:117)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
02-14 11:21:57 log: Error reading log file (non-fatal)
java.lang.NullPointerException
	at org.h2.store.DiskFile.initFromSummary(DiskFile.java:197)
	at org.h2.store.LogFile.redoOrUndo(LogFile.java:249)
	at org.h2.store.LogFile.redoAllGoEnd(LogFile.java:300)
	at org.h2.store.LogSystem.recover(LogSystem.java:166)
	at org.h2.engine.Database.open(Database.java:431)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:290)
	at org.executequery.datasource.ConnectionDataSource.getConnection(ConnectionDataSource.java:267)
	at org.executequery.datasource.ConnectionPool.ensureCapacity(ConnectionPool.java:291)
	at org.executequery.datasource.ConnectionManager.createDataSource(ConnectionManager.java:90)
	at org.executequery.databasemediators.ConnectionBuilder.connect(ConnectionBuilder.java:133)
	at org.executequery.databasemediators.ConnectionBuilder.access$000(ConnectionBuilder.java:44)
	at org.executequery.databasemediators.ConnectionBuilder$1.construct(ConnectionBuilder.java:117)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
02-14 11:22:51 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Check constraint violation: FOREIGN_1_REQUESTID_REPLICAID: PUBLIC.PROCESSEXECUTIONSTATEINFORMATION FOREIGN KEY(REQUESTID, REPLICAID) REFERENCES PUBLIC.APPLICATIONEXECUTIONSTATEINFORMATION(REQUESTID, REPLICAID) [23000-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:336)
	at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:352)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:230)
	at org.h2.table.Table.fireConstraints(Table.java:379)
	at org.h2.table.Table.fireAfterRow(Table.java:387)
	at org.h2.command.dml.Delete.update(Delete.java:75)
	at org.h2.command.CommandContainer.update(CommandContainer.java:64)
	at org.h2.command.Command.executeUpdate(Command.java:120)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:109)
	at org.executequery.databasemediators.QuerySender.updateRecords(QuerySender.java:1017)
	at org.executequery.databasemediators.QuerySender.executeQuery(QuerySender.java:868)
	at org.executequery.gui.editor.QueryAnalyser.executeSQL(QueryAnalyser.java:501)
	at org.executequery.gui.editor.QueryAnalyser.access$000(QueryAnalyser.java:66)
	at org.executequery.gui.editor.QueryAnalyser$1.construct(QueryAnalyser.java:298)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
02-14 11:22:51 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Check constraint violation: FOREIGN_2_REQUESTID: PUBLIC.APPLICATIONEXECUTIONSTATEINFORMATION FOREIGN KEY(REQUESTID) REFERENCES PUBLIC.APPLICATIONEXECUTIONINFORMATION(REQUESTID) [23000-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:336)
	at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:352)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:230)
	at org.h2.table.Table.fireConstraints(Table.java:379)
	at org.h2.table.Table.fireAfterRow(Table.java:387)
	at org.h2.command.dml.Delete.update(Delete.java:75)
	at org.h2.command.CommandContainer.update(CommandContainer.java:64)
	at org.h2.command.Command.executeUpdate(Command.java:120)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:109)
	at org.executequery.databasemediators.QuerySender.updateRecords(QuerySender.java:1017)
	at org.executequery.databasemediators.QuerySender.executeQuery(QuerySender.java:868)
	at org.executequery.gui.editor.QueryAnalyser.executeSQL(QueryAnalyser.java:501)
	at org.executequery.gui.editor.QueryAnalyser.access$000(QueryAnalyser.java:66)
	at org.executequery.gui.editor.QueryAnalyser$1.construct(QueryAnalyser.java:298)
	at org.underworldlabs.swing.util.SwingWorker$2.run(SwingWorker.java:138)
	at java.lang.Thread.run(Thread.java:595)
04-27 10:31:10 jdbc[0]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:950)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at org.h2.server.web.AppServer.getConnection(AppServer.java:231)
	at org.h2.server.web.AppThread.login(AppThread.java:516)
	at org.h2.server.web.AppThread.process(AppThread.java:55)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
04-27 10:34:05 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement DELETE *[*] FROM APPLICATIONEXECUTIONINFORMATION; expected identifier [42001-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSyntaxError(Message.java:77)
	at org.h2.command.Parser.readIdentifierWithSchema(Parser.java:1989)
	at org.h2.command.Parser.readIdentifierWithSchema(Parser.java:2006)
	at org.h2.command.Parser.readSimpleTableFilter(Parser.java:550)
	at org.h2.command.Parser.parseDelete(Parser.java:570)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
04-27 10:34:16 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Check constraint violation: FOREIGN_1_REQUESTID: PUBLIC.APPLICATIONEXECUTIONINFORMATION_AVAILABLEBINARIES FOREIGN KEY(REQUESTID) REFERENCES PUBLIC.APPLICATIONEXECUTIONINFORMATION(REQUESTID) [23000-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:336)
	at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:352)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:230)
	at org.h2.table.Table.fireConstraints(Table.java:379)
	at org.h2.table.Table.fireAfterRow(Table.java:387)
	at org.h2.command.dml.Delete.update(Delete.java:75)
	at org.h2.command.CommandContainer.update(CommandContainer.java:64)
	at org.h2.command.Command.executeUpdate(Command.java:120)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
04-27 10:34:47 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement DELETE *[*] FROM APPLICATIONEXECUTIONINFORMATION; expected identifier [42001-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSyntaxError(Message.java:77)
	at org.h2.command.Parser.readIdentifierWithSchema(Parser.java:1989)
	at org.h2.command.Parser.readIdentifierWithSchema(Parser.java:2006)
	at org.h2.command.Parser.readSimpleTableFilter(Parser.java:550)
	at org.h2.command.Parser.parseDelete(Parser.java:570)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
04-27 10:35:36 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement DELETE FROM APPLICATIONEXECUTIONINFORMATION  WHERE REQUESTID = *; expected ALL, ANY, SOME, SELECT, FROM [42001-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSyntaxError(Message.java:77)
	at org.h2.command.Parser.getSyntaxError(Parser.java:414)
	at org.h2.command.Parser.readTerm(Parser.java:1761)
	at org.h2.command.Parser.readFactor(Parser.java:1487)
	at org.h2.command.Parser.readSum(Parser.java:1474)
	at org.h2.command.Parser.readConcat(Parser.java:1466)
	at org.h2.command.Parser.readCondition(Parser.java:1432)
	at org.h2.command.Parser.readAnd(Parser.java:1328)
	at org.h2.command.Parser.readExpression(Parser.java:1320)
	at org.h2.command.Parser.parseDelete(Parser.java:573)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:222)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
04-27 10:35:44 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement DELETE FROM APPLICATIONEXECUTIONINFORMATION  WHERE REQUESTID = ALL; expected ( [42001-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSyntaxError(Message.java:77)
	at org.h2.command.Parser.read(Parser.java:2028)
	at org.h2.command.Parser.readCondition(Parser.java:1422)
	at org.h2.command.Parser.readAnd(Parser.java:1328)
	at org.h2.command.Parser.readExpression(Parser.java:1320)
	at org.h2.command.Parser.parseDelete(Parser.java:573)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
04-27 10:36:01 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement DELETE FROM APPLICATIONEXECUTIONINFORMATION  WHERE REQUESTID = ALL; expected ( [42001-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSyntaxError(Message.java:77)
	at org.h2.command.Parser.read(Parser.java:2028)
	at org.h2.command.Parser.readCondition(Parser.java:1422)
	at org.h2.command.Parser.readAnd(Parser.java:1328)
	at org.h2.command.Parser.readExpression(Parser.java:1320)
	at org.h2.command.Parser.parseDelete(Parser.java:573)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
04-27 10:36:17 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement DELETE *[*] FROM APPLICATIONEXECUTIONINFORMATION; expected identifier [42001-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSyntaxError(Message.java:77)
	at org.h2.command.Parser.readIdentifierWithSchema(Parser.java:1989)
	at org.h2.command.Parser.readIdentifierWithSchema(Parser.java:2006)
	at org.h2.command.Parser.readSimpleTableFilter(Parser.java:550)
	at org.h2.command.Parser.parseDelete(Parser.java:570)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
04-27 10:36:23 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement DELETE *[*] FROM APPLICATIONEXECUTIONINFORMATION; expected identifier [42001-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSyntaxError(Message.java:77)
	at org.h2.command.Parser.readIdentifierWithSchema(Parser.java:1989)
	at org.h2.command.Parser.readIdentifierWithSchema(Parser.java:2006)
	at org.h2.command.Parser.readSimpleTableFilter(Parser.java:550)
	at org.h2.command.Parser.parseDelete(Parser.java:570)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
04-27 10:36:25 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement DELETE *[*] FROM APPLICATIONEXECUTIONINFORMATION; expected identifier [42001-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSyntaxError(Message.java:77)
	at org.h2.command.Parser.readIdentifierWithSchema(Parser.java:1989)
	at org.h2.command.Parser.readIdentifierWithSchema(Parser.java:2006)
	at org.h2.command.Parser.readSimpleTableFilter(Parser.java:550)
	at org.h2.command.Parser.parseDelete(Parser.java:570)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
04-27 10:36:26 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement DELETE *[*] FROM APPLICATIONEXECUTIONINFORMATION; expected identifier [42001-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSyntaxError(Message.java:77)
	at org.h2.command.Parser.readIdentifierWithSchema(Parser.java:1989)
	at org.h2.command.Parser.readIdentifierWithSchema(Parser.java:2006)
	at org.h2.command.Parser.readSimpleTableFilter(Parser.java:550)
	at org.h2.command.Parser.parseDelete(Parser.java:570)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
04-27 10:36:27 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement DELETE *[*] FROM APPLICATIONEXECUTIONINFORMATION; expected identifier [42001-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSyntaxError(Message.java:77)
	at org.h2.command.Parser.readIdentifierWithSchema(Parser.java:1989)
	at org.h2.command.Parser.readIdentifierWithSchema(Parser.java:2006)
	at org.h2.command.Parser.readSimpleTableFilter(Parser.java:550)
	at org.h2.command.Parser.parseDelete(Parser.java:570)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
04-27 10:36:43 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement DELETE *[*] FROM APPLICATIONEXECUTIONINFORMATIONAPPLICATIONEXECUTIONINFORMATION_AVAILABLEBINARIES; expected identifier [42001-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSyntaxError(Message.java:77)
	at org.h2.command.Parser.readIdentifierWithSchema(Parser.java:1989)
	at org.h2.command.Parser.readIdentifierWithSchema(Parser.java:2006)
	at org.h2.command.Parser.readSimpleTableFilter(Parser.java:550)
	at org.h2.command.Parser.parseDelete(Parser.java:570)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
04-27 10:36:55 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Table ALL not found; SQL statement: DELETE ALL FROM APPLICATIONEXECUTIONINFORMATIONAPPLICATIONEXECUTIONINFORMATION_AVAILABLEBINARIES [42S02-36]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.parse(Parser.java:224)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
org.h2.jdbc.JdbcSQLException: Table ALL not found [42S02-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.schema.Schema.getTableOrView(Schema.java:199)
	at org.h2.command.Parser.readSimpleTableFilter(Parser.java:551)
	at org.h2.command.Parser.parseDelete(Parser.java:570)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
04-27 10:37:08 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Table APPLICATIONEXECUTIONINFORMATIONAPPLICATIONEXECUTIONINFORMATION_AVAILABLEBINARIES not found; SQL statement: DELETE FROM APPLICATIONEXECUTIONINFORMATIONAPPLICATIONEXECUTIONINFORMATION_AVAILABLEBINARIES [42S02-36]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.parse(Parser.java:224)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
org.h2.jdbc.JdbcSQLException: Table APPLICATIONEXECUTIONINFORMATIONAPPLICATIONEXECUTIONINFORMATION_AVAILABLEBINARIES not found [42S02-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.schema.Schema.getTableOrView(Schema.java:199)
	at org.h2.command.Parser.readSimpleTableFilter(Parser.java:551)
	at org.h2.command.Parser.parseDelete(Parser.java:570)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.parse(Parser.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
04-27 10:37:41 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Check constraint violation: FOREIGN_1_REQUESTID: PUBLIC.APPLICATIONEXECUTIONINFORMATION_AVAILABLEBINARIES FOREIGN KEY(REQUESTID) REFERENCES PUBLIC.APPLICATIONEXECUTIONINFORMATION(REQUESTID) [23000-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:336)
	at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:352)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:230)
	at org.h2.table.Table.fireConstraints(Table.java:379)
	at org.h2.table.Table.fireAfterRow(Table.java:387)
	at org.h2.command.dml.Delete.update(Delete.java:75)
	at org.h2.command.CommandContainer.update(CommandContainer.java:64)
	at org.h2.command.Command.executeUpdate(Command.java:120)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
04-27 10:37:52 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Check constraint violation: FOREIGN_1_REQUESTID: PUBLIC.APPLICATIONEXECUTIONINFORMATION_AVAILABLEBINARIES FOREIGN KEY(REQUESTID) REFERENCES PUBLIC.APPLICATIONEXECUTIONINFORMATION(REQUESTID) [23000-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:336)
	at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:352)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:230)
	at org.h2.table.Table.fireConstraints(Table.java:379)
	at org.h2.table.Table.fireAfterRow(Table.java:387)
	at org.h2.command.dml.Delete.update(Delete.java:75)
	at org.h2.command.CommandContainer.update(CommandContainer.java:64)
	at org.h2.command.Command.executeUpdate(Command.java:120)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
04-27 10:38:32 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Check constraint violation: FOREIGN_2_REQUESTID: PUBLIC.APPLICATIONEXECUTIONSTATEINFORMATION FOREIGN KEY(REQUESTID) REFERENCES PUBLIC.APPLICATIONEXECUTIONINFORMATION(REQUESTID) [23000-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:336)
	at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:352)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:230)
	at org.h2.table.Table.fireConstraints(Table.java:379)
	at org.h2.table.Table.fireAfterRow(Table.java:387)
	at org.h2.command.dml.Delete.update(Delete.java:75)
	at org.h2.command.CommandContainer.update(CommandContainer.java:64)
	at org.h2.command.Command.executeUpdate(Command.java:120)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
04-27 10:38:46 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Check constraint violation: FOREIGN_1_REQUESTID_REPLICAID: PUBLIC.PROCESSEXECUTIONSTATEINFORMATION FOREIGN KEY(REQUESTID, REPLICAID) REFERENCES PUBLIC.APPLICATIONEXECUTIONSTATEINFORMATION(REQUESTID, REPLICAID) [23000-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:336)
	at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:352)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:230)
	at org.h2.table.Table.fireConstraints(Table.java:379)
	at org.h2.table.Table.fireAfterRow(Table.java:387)
	at org.h2.command.dml.Delete.update(Delete.java:75)
	at org.h2.command.CommandContainer.update(CommandContainer.java:64)
	at org.h2.command.Command.executeUpdate(Command.java:120)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
06-26 11:53:39 jdbc[4]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:950)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:193)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.connection(ExecutionDatabaseManager.java:707)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.getLastProcessRestartId(ExecutionDatabaseManager.java:649)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.changeProcessExecutionStateToExecutingOrFailure(ExecutionDatabaseManager.java:243)
	at grm.executionManager.ExecutionManagerImpl.setProcessExecutionStarted(ExecutionManagerImpl.java:127)
	at clusterManagement.ExecutionManagerPOA._invoke(ExecutionManagerPOA.java:92)
	at org.jacorb.poa.RequestProcessor.invokeOperation(RequestProcessor.java:299)
	at org.jacorb.poa.RequestProcessor.process(RequestProcessor.java:593)
	at org.jacorb.poa.RequestProcessor.run(RequestProcessor.java:735)
06-26 12:01:58 log: Error reading log file (non-fatal)
java.lang.NullPointerException
	at org.h2.store.DiskFile.initFromSummary(DiskFile.java:197)
	at org.h2.store.LogFile.redoOrUndo(LogFile.java:249)
	at org.h2.store.LogFile.redoAllGoEnd(LogFile.java:300)
	at org.h2.store.LogSystem.recover(LogSystem.java:166)
	at org.h2.engine.Database.open(Database.java:431)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:193)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.connection(ExecutionDatabaseManager.java:707)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.registerApplicationExecution(ExecutionDatabaseManager.java:65)
	at grm.executionManager.ExecutionManagerImpl.setExecutionScheduled(ExecutionManagerImpl.java:75)
	at clusterManagement._ExecutionManagerStub.setExecutionScheduled(_ExecutionManagerStub.java:104)
	at grm.GrmImpl.requestRemoteExecution(GrmImpl.java:184)
	at clusterManagement.GrmPOA._invoke(GrmPOA.java:81)
	at org.jacorb.poa.RequestProcessor.invokeOperation(RequestProcessor.java:299)
	at org.jacorb.poa.RequestProcessor.process(RequestProcessor.java:593)
	at org.jacorb.poa.RequestProcessor.run(RequestProcessor.java:735)
06-26 12:02:00 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Connection is broken [90067-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.message.Message.getSQLException(Message.java:88)
	at org.h2.command.Prepared.needRecompile(Prepared.java:33)
	at org.h2.command.CommandContainer.recompileIfRequired(CommandContainer.java:38)
	at org.h2.command.CommandContainer.query(CommandContainer.java:68)
	at org.h2.command.Command.executeQueryLocal(Command.java:72)
	at org.h2.command.Command.executeQuery(Command.java:61)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:86)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.getLastProcessRestartId(ExecutionDatabaseManager.java:655)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.changeProcessExecutionStateToExecutingOrFailure(ExecutionDatabaseManager.java:243)
	at grm.executionManager.ExecutionManagerImpl.setProcessExecutionStarted(ExecutionManagerImpl.java:127)
	at clusterManagement.ExecutionManagerPOA._invoke(ExecutionManagerPOA.java:92)
	at org.jacorb.poa.RequestProcessor.invokeOperation(RequestProcessor.java:299)
	at org.jacorb.poa.RequestProcessor.process(RequestProcessor.java:593)
	at org.jacorb.poa.RequestProcessor.run(RequestProcessor.java:735)
06-26 13:20:22 database: opening /auto/home/pos/vinicius/integrade/trunk/integrade/clusterManagement/grm/database/ExecutionManager
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:424)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:193)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.connection(ExecutionDatabaseManager.java:720)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.registerApplicationExecution(ExecutionDatabaseManager.java:65)
	at grm.executionManager.ExecutionManagerImpl.setExecutionScheduled(ExecutionManagerImpl.java:75)
	at clusterManagement._ExecutionManagerStub.setExecutionScheduled(_ExecutionManagerStub.java:104)
	at grm.GrmImpl.requestRemoteExecution(GrmImpl.java:184)
	at clusterManagement.GrmPOA._invoke(GrmPOA.java:81)
	at org.jacorb.poa.RequestProcessor.invokeOperation(RequestProcessor.java:299)
	at org.jacorb.poa.RequestProcessor.process(RequestProcessor.java:593)
	at org.jacorb.poa.RequestProcessor.run(RequestProcessor.java:735)
06-26 13:24:01 jdbc[2]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:950)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:193)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.connection(ExecutionDatabaseManager.java:720)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.getLastProcessRestartId(ExecutionDatabaseManager.java:658)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.changeProcessExecutionStateToExecutingOrFailure(ExecutionDatabaseManager.java:243)
	at grm.executionManager.ExecutionManagerImpl.setProcessExecutionStarted(ExecutionManagerImpl.java:127)
	at clusterManagement.ExecutionManagerPOA._invoke(ExecutionManagerPOA.java:92)
	at org.jacorb.poa.RequestProcessor.invokeOperation(RequestProcessor.java:299)
	at org.jacorb.poa.RequestProcessor.process(RequestProcessor.java:593)
	at org.jacorb.poa.RequestProcessor.run(RequestProcessor.java:735)
06-26 13:24:01 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Connection is broken [90067-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.message.Message.getSQLException(Message.java:88)
	at org.h2.command.Prepared.needRecompile(Prepared.java:33)
	at org.h2.command.CommandContainer.recompileIfRequired(CommandContainer.java:38)
	at org.h2.command.CommandContainer.query(CommandContainer.java:68)
	at org.h2.command.Command.executeQueryLocal(Command.java:72)
	at org.h2.command.Command.executeQuery(Command.java:61)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:86)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.getLastProcessRestartId(ExecutionDatabaseManager.java:664)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.changeProcessExecutionStateToExecutingOrFailure(ExecutionDatabaseManager.java:243)
	at grm.executionManager.ExecutionManagerImpl.setProcessExecutionStarted(ExecutionManagerImpl.java:127)
	at clusterManagement.ExecutionManagerPOA._invoke(ExecutionManagerPOA.java:92)
	at org.jacorb.poa.RequestProcessor.invokeOperation(RequestProcessor.java:299)
	at org.jacorb.poa.RequestProcessor.process(RequestProcessor.java:593)
	at org.jacorb.poa.RequestProcessor.run(RequestProcessor.java:735)
06-26 14:04:38 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Connection is broken [90067-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.message.Message.getSQLException(Message.java:88)
	at org.h2.command.Prepared.needRecompile(Prepared.java:33)
	at org.h2.command.CommandContainer.recompileIfRequired(CommandContainer.java:38)
	at org.h2.command.CommandContainer.query(CommandContainer.java:68)
	at org.h2.command.Command.executeQueryLocal(Command.java:72)
	at org.h2.command.Command.executeQuery(Command.java:61)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:86)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.getLastProcessRestartId(ExecutionDatabaseManager.java:664)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.changeProcessExecutionStateToExecutingOrFailure(ExecutionDatabaseManager.java:243)
	at grm.executionManager.ExecutionManagerImpl.setProcessExecutionStarted(ExecutionManagerImpl.java:127)
	at clusterManagement.ExecutionManagerPOA._invoke(ExecutionManagerPOA.java:92)
	at org.jacorb.poa.RequestProcessor.invokeOperation(RequestProcessor.java:299)
	at org.jacorb.poa.RequestProcessor.process(RequestProcessor.java:593)
	at org.jacorb.poa.RequestProcessor.run(RequestProcessor.java:735)
06-26 14:21:29 log: Error reading log file (non-fatal)
java.lang.NullPointerException
	at org.h2.store.DiskFile.initFromSummary(DiskFile.java:197)
	at org.h2.store.LogFile.redoOrUndo(LogFile.java:249)
	at org.h2.store.LogFile.redoAllGoEnd(LogFile.java:300)
	at org.h2.store.LogSystem.recover(LogSystem.java:166)
	at org.h2.engine.Database.open(Database.java:431)
	at org.h2.engine.Database.<init>(Database.java:382)
	at org.h2.engine.Engine.openSession(Engine.java:44)
	at org.h2.engine.Engine.getSession(Engine.java:85)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:939)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:193)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.connection(ExecutionDatabaseManager.java:723)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.prepareStatement(ExecutionDatabaseManager.java:748)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.registerApplicationExecution(ExecutionDatabaseManager.java:65)
	at grm.executionManager.ExecutionManagerImpl.setExecutionScheduled(ExecutionManagerImpl.java:75)
	at clusterManagement._ExecutionManagerStub.setExecutionScheduled(_ExecutionManagerStub.java:104)
	at grm.GrmImpl.requestRemoteExecution(GrmImpl.java:184)
	at clusterManagement.GrmPOA._invoke(GrmPOA.java:81)
	at org.jacorb.poa.RequestProcessor.invokeOperation(RequestProcessor.java:299)
	at org.jacorb.poa.RequestProcessor.process(RequestProcessor.java:593)
	at org.jacorb.poa.RequestProcessor.run(RequestProcessor.java:735)
06-26 14:23:56 jdbc[2]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:950)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:193)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.connection(ExecutionDatabaseManager.java:723)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.prepareStatement(ExecutionDatabaseManager.java:748)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.getLastProcessRestartId(ExecutionDatabaseManager.java:659)
	at grm.executionManager.dataBase.ExecutionDatabaseManager.changeProcessExecutionStateToExecutingOrFailure(ExecutionDatabaseManager.java:243)
	at grm.executionManager.ExecutionManagerImpl.setProcessExecutionStarted(ExecutionManagerImpl.java:127)
	at clusterManagement.ExecutionManagerPOA._invoke(ExecutionManagerPOA.java:92)
	at org.jacorb.poa.RequestProcessor.invokeOperation(RequestProcessor.java:299)
	at org.jacorb.poa.RequestProcessor.process(RequestProcessor.java:593)
	at org.jacorb.poa.RequestProcessor.run(RequestProcessor.java:735)
08-24 11:23:42 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement SELECT * FROM APPLICATIONEXECUTIONINFORMATION APPLICATIONEXECUTIONINFORMATION_AVAILABLEBINARIES APPLICATIONEXECUTIONSTATEINFORMATION [42000-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.message.Message.getSyntaxError(Message.java:72)
	at org.h2.command.Parser.getSyntaxError(Parser.java:405)
	at org.h2.command.Parser.prepareCommand(Parser.java:206)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
08-28 19:41:51 jdbc[0]: Connection not closed
java.lang.Exception: Stack Trace
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:950)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at org.h2.server.web.AppServer.getConnection(AppServer.java:231)
	at org.h2.server.web.AppThread.login(AppThread.java:516)
	at org.h2.server.web.AppThread.process(AppThread.java:55)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
09-01 14:42:52 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement SELECT * FROMAPPLICATIONEXECUTIONINFORMATION[*] 

CREATE CACHED TABLE PUBLIC.APPLICATIONEXECUTIONINFORMATION(
    REQUESTID VARCHAR(2147483647) NOT NULL,
    REQUESTINGASCTIOR VARCHAR(2147483647) NOT NULL,
    SOURCE VARCHAR(10) NOT NULL,
    ORIGINALGRMIOR VARCHAR(2147483647) NOT NULL,
    PREVIOUSGRMIOR VARCHAR(2147483647) NOT NULL,
    APPLICATIONREPOSITORYIOR VARCHAR(2147483647) NOT NULL,
    BASEPATH VARCHAR(2147483647) NOT NULL,
    APPLICATIONNAME VARCHAR(2147483647) NOT NULL,
    APPLICATIONCONSTRAINTS VARCHAR(2147483647),
    APPLICATIONPREFERENCES VARCHAR(2147483647),
    APPLICATIONTYPE TINYINT NOT NULL,
    FORCEDIFFERENTNODES BOOLEAN NOT NULL,
    USERID VARCHAR(2147483647) NOT NULL
)  [42000-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.message.Message.getSyntaxError(Message.java:72)
	at org.h2.command.Parser.getSyntaxError(Parser.java:405)
	at org.h2.command.Parser.prepareCommand(Parser.java:206)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
09-01 14:50:38 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Table APPLICATIONEXECUTIONINFORMARTION not found [42S02-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.command.ddl.DropTable.prepareDrop(DropTable.java:54)
	at org.h2.command.ddl.DropTable.update(DropTable.java:83)
	at org.h2.command.CommandContainer.update(CommandContainer.java:64)
	at org.h2.command.Command.executeUpdate(Command.java:120)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
09-01 15:07:13 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement CREATE CACHED TABLE PUBLIC.APPLICATIONEXECUTIONINFORMATION(
    EXECUTIONID VARCHAR(2147483647) NOT NULL,
    REQUESTID VARCHAR(2147483647) NOT NULL,
    PROCESSID VARCHAR(2147483647) NOT NULL,
    REQUISITINGASCTIOR VARCHAR(2147483647) NOT NULL,
    ORIGINALGRMIOR VARCHAR(2147483647) NOT NULL,
    APPLICATIONARGUMENTS VARCHAR(2147483647),
    APPLICATIONSTATE VARCHAR(2147483647),
    APPLICATIONREPOSITORYID VARCHAR(2147483647) NOT NULL,
    APPLICATIONNAME VARCHAR(2147483647) NOT NULL,
    APPLICATIONCONSTRAINTS VARCHAR(2147483647),
    APPLICATIONPREFERENCES VARCHAR(2147483647),
    APPLICATIONTYPE VARCHAR(2147483647),
    FINISHTIMESTAMP VARCHAR(2147483647)
    SOURCE[*] VARCHAR(10) NOT NULL,
    USERID VARCHAR(2147483647) NOT NULL
); expected ) [42001-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSyntaxError(Message.java:77)
	at org.h2.command.Parser.read(Parser.java:2028)
	at org.h2.command.Parser.parseCreateTable(Parser.java:3825)
	at org.h2.command.Parser.parseCreate(Parser.java:2837)
	at org.h2.command.Parser.parse(Parser.java:267)
	at org.h2.command.Parser.parse(Parser.java:218)
	at org.h2.command.Parser.prepareCommand(Parser.java:189)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:982)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
09-01 15:16:24 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Null value not allowed for column SOURCE [90006-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:172)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:269)
	at org.h2.command.dml.Insert.update(Insert.java:85)
	at org.h2.command.CommandContainer.update(CommandContainer.java:64)
	at org.h2.command.Command.executeUpdate(Command.java:120)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:158)
	at core.execman.ema.dataBase.ExecutionDatabaseManager.registerApplicationExecution(ExecutionDatabaseManager.java:98)
	at core.execman.ema.ExecutionManagementAgentImpl.registerAgent(ExecutionManagementAgentImpl.java:98)
	at core.execman.ema.behaviours.ReceiveRegisterAgentRequest.prepareResultNotification(ReceiveRegisterAgentRequest.java:74)
	at jade.proto.AchieveREResponder$PrepareResult.action(Unknown Source)
	at jade.core.behaviours.Behaviour.actionWrapper(Unknown Source)
	at jade.core.behaviours.CompositeBehaviour.action(Unknown Source)
	at jade.core.behaviours.Behaviour.actionWrapper(Unknown Source)
	at jade.core.Agent$ActiveLifeCycle.execute(Unknown Source)
	at jade.core.Agent.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:595)
09-01 15:24:49 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Table PROCESSEXECUTIONSTATEINFORMATION already exists [42S01-36]
	at org.h2.message.Message.getSQLException(Message.java:67)
	at org.h2.message.Message.getSQLException(Message.java:49)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:93)
	at org.h2.command.CommandContainer.update(CommandContainer.java:64)
	at org.h2.command.Command.executeUpdate(Command.java:120)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:155)
	at org.h2.server.web.AppThread.getResult(AppThread.java:915)
	at org.h2.server.web.AppThread.query(AppThread.java:593)
	at org.h2.server.web.AppThread.process(AppThread.java:67)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
